"""empty message

Revision ID: 337290720422
Revises: f31b88b322b7
Create Date: 2023-06-15 22:45:32.332254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337290720422'
down_revision = 'f31b88b322b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meeting_link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_groups')
    # ### end Alembic commands ###
